variables:
    NO_INTERACTION: "1"
    REPORT_EXIT_STATUS: "1"
    DEBIAN_FRONTEND: "noninteractive"

before_script:
    - apt-get update
    - apt-get install -y lcov valgrind
    - curl -L https://phar.phpunit.de/phpunit.phar > /usr/local/bin/phpunit
    - chmod +x /usr/local/bin/phpunit

after_script:
    - ./run-tests.sh after_failure

test:7.0-nts:
    image: jbboehr/php-cgi:7.0-nts
    script:
        - ./run-tests.sh userland
        - ./run-tests.sh coverage
        - ./run-tests.sh valgrind

test:7.0-zts:
    image: jbboehr/php-cgi:7.0-zts
    script:
        - ./run-tests.sh userland
        - ./run-tests.sh coverage
        - ./run-tests.sh valgrind

test:7.1-nts:
    image: jbboehr/php-cgi:7.0-nts
    script:
        - ./run-tests.sh userland
        - ./run-tests.sh coverage
        - ./run-tests.sh valgrind

test:7.1-zts:
    image: jbboehr/php-cgi:7.0-zts
    script:
        - ./run-tests.sh userland
        - ./run-tests.sh coverage
        - ./run-tests.sh valgrind

test:5.6-nts:
    image: jbboehr/php-cgi:5.6-nts
    script:
        - ./run-tests.sh userland

test:5.6-zts:
    image: jbboehr/php-cgi:5.6-zts
    script:
        - ./run-tests.sh userland

